export const people = [
  "Ai",
  "Brie",
  "Delfina",
  "Emma",
  "Hayley W",
  "Hayley S",
  "Jaime",
  "Lucy",
  "Mario",
  "Mimmi",
  "Moya",
  "Nicola",
];

export const avatars = [
  "aquarium",
  "bat",
  "bee",
  "bird",
  "butterfly",
  "chick",
  "crab",
  "dog",
  "dolphin",
  "eagle",
  "eel",
  "flamingo",
  "hen",
  "jellyfish",
  "kennary",
  "ladybug",
  "manta ray",
  "mosquito",
  "panther",
  "parrot",
  "penguin",
  "pig",
  "plankton",
  "polar-bear",
  "seagull",
  "seal",
  "shrimp",
  "sloth",
  "snail",
  "snake",
  "squid",
  "starfish",
  "swan",
  "tang-fish",
  "tick",
  "tortoise",
  "turtle",
  "worm",
];

export const questions = [
  "What are you having for lunch?",
  "How long have you been at Envato?",
  "Which team are you in?",
  "What is the most interesting thing on your desk?",
  "Which timezone are you in?",
  "Preferred mode of transport?",
  "Find a gif that best represents your mood right now",
  "Early bird or night owl?",
  "What is your karaoke song?",
  "What do you like to do outside of work?",
  "What advice do you have for our new apprentices?",
];
